import random

# Generate unique comments for each sentiment
positive_comments = [
    "This product exceeded all my expectations", "Absolutely fantastic quality and service", "Best investment I've made this year",
    "Outstanding customer support team", "Incredible attention to detail", "Perfect solution for my needs",
    "Highly impressed with the results", "Exceptional value for the price", "Amazing user experience overall",
    "Top-notch build quality", "Brilliant design and functionality", "Superb performance every time",
    "Love how easy it is to use", "Fantastic features and capabilities", "Outstanding technical support",
    "Excellent problem-solving tool", "Great return on investment", "Wonderful product design",
    "Impressive innovation and quality", "Best-in-class performance", "Amazing customer service experience",
    "Perfect for professional use", "Highly recommend to everyone", "Exceptional reliability and durability",
    "Outstanding value proposition", "Brilliant engineering work", "Fantastic user interface design",
    "Excellent documentation provided", "Great community support", "Amazing product updates",
    "Perfect integration capabilities", "Outstanding security features", "Excellent scalability options",
    "Great customization possibilities", "Amazing performance optimization", "Perfect workflow integration",
    "Outstanding data analytics", "Excellent mobile compatibility", "Great API documentation",
    "Amazing cloud integration", "Perfect automation features", "Outstanding reporting capabilities",
    "Excellent backup solutions", "Great collaboration tools", "Amazing real-time updates",
    "Perfect dashboard design", "Outstanding notification system", "Excellent search functionality",
    "Great export options", "Amazing import capabilities", "Perfect user management",
    "Outstanding access controls", "Excellent audit trails", "Great compliance features",
    "Amazing disaster recovery", "Perfect load balancing", "Outstanding caching system",
    "Excellent monitoring tools", "Great logging capabilities", "Amazing error handling",
    "Perfect debugging features", "Outstanding code quality", "Excellent testing framework",
    "Great deployment process", "Amazing CI/CD pipeline", "Perfect version control",
    "Outstanding documentation", "Excellent training materials", "Great onboarding process",
    "Amazing support resources", "Perfect knowledge base", "Outstanding FAQ section",
    "Excellent video tutorials", "Great webinar content", "Amazing conference presentations",
    "Perfect case studies", "Outstanding white papers", "Excellent research reports",
    "Great industry insights", "Amazing trend analysis", "Perfect market research",
    "Outstanding competitive analysis", "Excellent benchmarking", "Great performance metrics",
    "Amazing ROI calculations", "Perfect cost analysis", "Outstanding budget planning",
    "Excellent resource allocation", "Great project management", "Amazing team collaboration",
    "Perfect communication tools", "Outstanding meeting features", "Excellent file sharing",
    "Great version tracking", "Amazing change management", "Perfect approval workflows",
    "Outstanding task management", "Excellent time tracking", "Great milestone tracking",
    "Amazing progress reporting", "Perfect status updates", "Outstanding deadline management",
    "Excellent priority setting", "Great resource planning", "Amazing capacity management",
    "Perfect workload distribution", "Outstanding team productivity", "Excellent efficiency gains",
    "Great time savings", "Amazing cost reductions", "Perfect quality improvements",
    "Outstanding customer satisfaction", "Excellent user adoption", "Great engagement metrics",
    "Amazing retention rates", "Perfect conversion rates", "Outstanding growth metrics",
    "Excellent revenue impact", "Great profit margins", "Amazing market share",
    "Perfect brand recognition", "Outstanding reputation", "Excellent customer loyalty",
    "Great word-of-mouth marketing", "Amazing viral growth", "Perfect organic reach",
    "Outstanding social media presence", "Excellent content marketing", "Great SEO performance",
    "Amazing search rankings", "Perfect website traffic", "Outstanding conversion optimization",
    "Excellent A/B testing", "Great user behavior analysis", "Amazing heat map insights",
    "Perfect funnel optimization", "Outstanding lead generation", "Excellent sales pipeline",
    "Great deal closure rates", "Amazing customer acquisition", "Perfect retention strategies",
    "Outstanding churn reduction", "Excellent lifetime value", "Great upselling success",
    "Amazing cross-selling results", "Perfect customer segmentation", "Outstanding personalization",
    "Excellent recommendation engine", "Great predictive analytics", "Amazing machine learning",
    "Perfect AI integration", "Outstanding automation", "Excellent workflow optimization",
    "Great process improvement", "Amazing operational efficiency", "Perfect system integration",
    "Outstanding data migration", "Excellent legacy support", "Great backward compatibility",
    "Amazing forward compatibility", "Perfect future-proofing", "Outstanding innovation pipeline",
    "Excellent roadmap planning", "Great feature prioritization", "Amazing development speed",
    "Perfect release management", "Outstanding quality assurance", "Excellent bug tracking",
    "Great issue resolution", "Amazing customer feedback", "Perfect feature requests",
    "Outstanding enhancement delivery", "Excellent maintenance support", "Great update frequency",
    "Amazing patch management", "Perfect security updates", "Outstanding vulnerability fixes",
    "Excellent threat protection", "Great risk mitigation", "Amazing compliance adherence",
    "Perfect regulatory support", "Outstanding audit readiness", "Excellent governance framework",
    "Great policy enforcement", "Amazing access management", "Perfect identity verification",
    "Outstanding single sign-on", "Excellent multi-factor auth", "Great password policies",
    "Amazing encryption standards", "Perfect data protection", "Outstanding privacy controls",
    "Excellent GDPR compliance", "Great CCPA adherence", "Amazing HIPAA support",
    "Perfect SOX compliance", "Outstanding PCI DSS", "Excellent ISO certification",
    "Great security frameworks", "Amazing penetration testing", "Perfect vulnerability scanning",
    "Outstanding threat modeling", "Excellent incident response", "Great disaster planning",
    "Amazing business continuity", "Perfect risk assessment", "Outstanding impact analysis",
    "Excellent mitigation strategies", "Great contingency planning", "Amazing recovery procedures",
    "Perfect backup verification", "Outstanding restore testing", "Excellent failover systems",
    "Great redundancy planning", "Amazing high availability", "Perfect uptime guarantees",
    "Outstanding SLA compliance", "Excellent performance monitoring", "Great capacity planning",
    "Amazing scalability testing", "Perfect load testing", "Outstanding stress testing",
    "Excellent performance tuning", "Great optimization results", "Amazing speed improvements",
    "Perfect response times", "Outstanding throughput gains", "Excellent latency reduction",
    "Great bandwidth efficiency", "Amazing resource utilization", "Perfect cost optimization",
    "Outstanding budget control", "Excellent expense tracking", "Great financial reporting",
    "Amazing profit analysis", "Perfect cost allocation", "Outstanding ROI measurement",
    "Excellent value demonstration", "Great business case", "Amazing stakeholder buy-in",
    "Perfect executive support", "Outstanding leadership backing", "Excellent team alignment",
    "Great organizational change", "Amazing cultural transformation", "Perfect adoption success",
    "Outstanding change management", "Excellent training delivery", "Great skill development",
    "Amazing competency building", "Perfect knowledge transfer", "Outstanding expertise growth",
    "Excellent career advancement", "Great professional development", "Amazing learning opportunities",
    "Perfect certification paths", "Outstanding skill validation", "Excellent competency assessment",
    "Great performance evaluation", "Amazing feedback systems", "Perfect coaching support",
    "Outstanding mentorship programs", "Excellent leadership development", "Great succession planning",
    "Amazing talent retention", "Perfect employee satisfaction", "Outstanding workplace culture",
    "Excellent team dynamics", "Great collaboration spirit", "Amazing innovation mindset",
    "Perfect continuous improvement", "Outstanding quality culture", "Excellent customer focus",
    "Great market orientation", "Amazing competitive advantage", "Perfect strategic positioning",
    "Outstanding brand differentiation", "Excellent value proposition", "Great unique selling points",
    "Amazing market penetration", "Perfect customer acquisition", "Outstanding market expansion",
    "Excellent geographic growth", "Great demographic reach", "Amazing segment targeting",
    "Perfect niche domination", "Outstanding category leadership", "Excellent industry recognition",
    "Great award achievements", "Amazing media coverage", "Perfect public relations",
    "Outstanding thought leadership", "Excellent expert positioning", "Great industry influence",
    "Amazing conference speaking", "Perfect panel participation", "Outstanding keynote delivery",
    "Excellent workshop facilitation", "Great training sessions", "Amazing educational content",
    "Perfect knowledge sharing", "Outstanding community building", "Excellent network effects",
    "Great ecosystem development", "Amazing partnership strategy", "Perfect alliance management",
    "Outstanding vendor relations", "Excellent supplier partnerships", "Great channel development",
    "Amazing distribution network", "Perfect market coverage", "Outstanding sales reach",
    "Excellent revenue generation", "Great profit maximization", "Amazing growth acceleration",
    "Perfect scaling success", "Outstanding expansion results", "Excellent market capture",
    "Great competitive positioning", "Amazing differentiation strategy", "Perfect value creation",
    "Outstanding customer delight", "Excellent satisfaction scores", "Great loyalty metrics",
    "Amazing advocacy rates", "Perfect referral programs", "Outstanding testimonials",
    "Excellent case studies", "Great success stories", "Amazing transformation examples",
    "Perfect implementation results", "Outstanding deployment success", "Excellent go-live experience",
    "Great user onboarding", "Amazing adoption curves", "Perfect utilization rates",
    "Outstanding engagement levels", "Excellent activity metrics", "Great usage patterns",
    "Amazing behavior insights", "Perfect analytics dashboard", "Outstanding reporting suite",
    "Excellent data visualization", "Great chart capabilities", "Amazing graph options",
    "Perfect table formatting", "Outstanding export features", "Excellent sharing options",
    "Great collaboration tools", "Amazing real-time editing", "Perfect version control",
    "Outstanding change tracking", "Excellent comment system", "Great review workflows",
    "Amazing approval processes", "Perfect notification alerts", "Outstanding reminder system",
    "Excellent calendar integration", "Great scheduling features", "Amazing meeting coordination",
    "Perfect agenda management", "Outstanding action items", "Excellent follow-up tracking",
    "Great task assignment", "Amazing progress monitoring", "Perfect status reporting",
    "Outstanding milestone celebration", "Excellent achievement recognition", "Great success acknowledgment"
]

negative_comments = [
    "Completely disappointed with this purchase", "Worst customer service I've ever experienced", "Total waste of money and time",
    "Extremely poor build quality", "Absolutely terrible user interface", "Major functionality issues throughout",
    "Completely unreliable and buggy", "Horrible performance and speed", "Terrible documentation and support",
    "Completely broken out of the box", "Worst investment decision ever", "Extremely frustrating to use daily",
    "Absolutely no value for money", "Terrible integration capabilities", "Completely useless for business",
    "Worst technical support team", "Extremely slow response times", "Absolutely no problem resolution",
    "Terrible software architecture", "Completely outdated technology", "Worst security implementation",
    "Extremely vulnerable to attacks", "Absolutely no data protection", "Terrible privacy controls",
    "Completely non-compliant system", "Worst audit trail ever", "Extremely poor access controls",
    "Absolutely no user management", "Terrible authentication system", "Completely broken authorization",
    "Worst single sign-on implementation", "Extremely poor password policies", "Absolutely no encryption",
    "Terrible backup solutions", "Completely unreliable recovery", "Worst disaster planning ever",
    "Extremely poor business continuity", "Absolutely no failover systems", "Terrible redundancy planning",
    "Completely inadequate uptime", "Worst SLA violations ever", "Extremely poor performance monitoring",
    "Absolutely no capacity planning", "Terrible scalability issues", "Completely failed load testing",
    "Worst stress test results", "Extremely poor optimization", "Absolutely no speed improvements",
    "Terrible response times", "Completely inadequate throughput", "Worst latency issues ever",
    "Extremely poor bandwidth usage", "Absolutely no resource efficiency", "Terrible cost optimization",
    "Completely blown budget", "Worst expense tracking ever", "Extremely poor financial reporting",
    "Absolutely no profit analysis", "Terrible cost allocation", "Completely failed ROI measurement",
    "Worst value demonstration ever", "Extremely poor business case", "Absolutely no stakeholder support",
    "Terrible executive backing", "Completely failed leadership", "Worst team alignment ever",
    "Extremely poor change management", "Absolutely no cultural fit", "Terrible adoption rates",
    "Completely failed training", "Worst skill development ever", "Extremely poor knowledge transfer",
    "Absolutely no expertise growth", "Terrible career impact", "Completely failed development",
    "Worst learning experience ever", "Extremely poor certification", "Absolutely no skill validation",
    "Terrible performance evaluation", "Completely broken feedback", "Worst coaching support ever",
    "Extremely poor mentorship", "Absolutely no leadership development", "Terrible succession planning",
    "Completely failed talent retention", "Worst employee satisfaction", "Extremely toxic workplace culture",
    "Absolutely terrible team dynamics", "Terrible collaboration experience", "Completely stifled innovation",
    "Worst improvement processes", "Extremely poor quality culture", "Absolutely no customer focus",
    "Terrible market orientation", "Completely lost competitive edge", "Worst strategic positioning",
    "Extremely poor brand image", "Absolutely no value proposition", "Terrible selling points",
    "Completely failed market penetration", "Worst customer acquisition", "Extremely poor expansion",
    "Absolutely no geographic growth", "Terrible demographic reach", "Completely missed targeting",
    "Worst niche performance", "Extremely poor category position", "Absolutely no industry recognition",
    "Terrible award track record", "Completely negative media coverage", "Worst public relations disaster",
    "Extremely poor thought leadership", "Absolutely no expert credibility", "Terrible industry influence",
    "Completely failed conference speaking", "Worst panel participation", "Extremely poor keynote delivery",
    "Absolutely terrible workshop facilitation", "Terrible training delivery", "Completely useless content",
    "Worst knowledge sharing", "Extremely poor community building", "Absolutely no network effects",
    "Terrible ecosystem development", "Completely failed partnerships", "Worst alliance management",
    "Extremely poor vendor relations", "Absolutely terrible suppliers", "Terrible channel development",
    "Completely broken distribution", "Worst market coverage", "Extremely poor sales reach",
    "Absolutely no revenue generation", "Terrible profit performance", "Completely stagnant growth",
    "Worst scaling failure", "Extremely poor expansion results", "Absolutely no market capture",
    "Terrible competitive position", "Completely failed differentiation", "Worst value destruction",
    "Extremely poor customer experience", "Absolutely terrible satisfaction", "Terrible loyalty metrics",
    "Completely failed advocacy", "Worst referral programs", "Extremely negative testimonials",
    "Absolutely terrible case studies", "Terrible failure stories", "Completely disastrous examples",
    "Worst implementation disaster", "Extremely failed deployment", "Absolutely terrible go-live",
    "Terrible user onboarding", "Completely failed adoption", "Worst utilization rates",
    "Extremely poor engagement", "Absolutely terrible metrics", "Terrible usage patterns",
    "Completely useless insights", "Worst analytics dashboard", "Extremely poor reporting",
    "Absolutely terrible visualization", "Terrible chart quality", "Completely broken graphs",
    "Worst table formatting", "Extremely poor export", "Absolutely no sharing options",
    "Terrible collaboration tools", "Completely broken editing", "Worst version control",
    "Extremely poor change tracking", "Absolutely no comment system", "Terrible review workflows",
    "Completely broken approvals", "Worst notification system", "Extremely poor reminders",
    "Absolutely no calendar integration", "Terrible scheduling features", "Completely failed coordination",
    "Worst agenda management", "Extremely poor action items", "Absolutely no follow-up",
    "Terrible task assignment", "Completely broken monitoring", "Worst status reporting",
    "Extremely poor milestone tracking", "Absolutely no recognition", "Terrible acknowledgment system",
    "Completely failed project management", "Worst resource allocation", "Extremely poor planning",
    "Absolutely no capacity management", "Terrible workload distribution", "Completely failed productivity",
    "Worst efficiency losses", "Extremely poor time management", "Absolutely no cost savings",
    "Terrible quality degradation", "Completely failed satisfaction", "Worst adoption failure",
    "Extremely poor engagement", "Absolutely terrible retention", "Terrible conversion rates",
    "Completely failed growth", "Worst revenue impact", "Extremely poor margins",
    "Absolutely no market share", "Terrible brand damage", "Completely destroyed reputation",
    "Worst customer relations", "Extremely negative word-of-mouth", "Absolutely no viral potential",
    "Terrible organic reach", "Completely failed social media", "Worst content performance",
    "Extremely poor SEO results", "Absolutely terrible rankings", "Terrible website performance",
    "Completely failed optimization", "Worst A/B testing", "Extremely poor analysis",
    "Absolutely no insights", "Terrible funnel performance", "Completely failed lead generation",
    "Worst sales pipeline", "Extremely poor closure rates", "Absolutely no acquisition",
    "Terrible retention strategies", "Completely failed churn reduction", "Worst lifetime value",
    "Extremely poor upselling", "Absolutely no cross-selling", "Terrible segmentation",
    "Completely failed personalization", "Worst recommendation engine", "Extremely poor analytics",
    "Absolutely no machine learning", "Terrible AI implementation", "Completely broken automation",
    "Worst workflow design", "Extremely poor optimization", "Absolutely no efficiency gains",
    "Terrible system integration", "Completely failed migration", "Worst legacy support",
    "Extremely poor compatibility", "Absolutely no future-proofing", "Terrible innovation pipeline",
    "Completely failed roadmap", "Worst feature prioritization", "Extremely slow development",
    "Absolutely terrible release management", "Terrible quality assurance", "Completely broken tracking",
    "Worst issue resolution", "Extremely poor feedback", "Absolutely no feature delivery",
    "Terrible enhancement process", "Completely failed maintenance", "Worst update frequency",
    "Extremely poor patch management", "Absolutely no security updates", "Terrible vulnerability handling",
    "Completely exposed threats", "Worst risk management", "Extremely poor compliance",
    "Absolutely no regulatory support", "Terrible audit readiness", "Completely failed governance",
    "Worst policy enforcement", "Extremely poor access management", "Absolutely no identity verification"
]

neutral_comments = [
    "The product works as advertised", "Standard functionality is present", "Meets basic operational requirements",
    "Average performance for this category", "Typical features for the price point", "Standard user interface design",
    "Regular customer support response", "Normal installation process", "Standard documentation provided",
    "Adequate for basic business needs", "Typical integration capabilities", "Standard security features included",
    "Regular backup functionality", "Normal system performance", "Standard reporting capabilities",
    "Adequate user management", "Typical authentication system", "Standard access controls",
    "Regular update schedule", "Normal maintenance requirements", "Standard compliance features",
    "Adequate monitoring tools", "Typical scalability options", "Standard performance metrics",
    "Regular cost structure", "Normal pricing model", "Standard licensing terms",
    "Adequate training materials", "Typical learning curve", "Standard onboarding process",
    "Regular support channels", "Normal response times", "Standard troubleshooting guides",
    "Adequate customization options", "Typical configuration settings", "Standard workflow capabilities",
    "Regular data export options", "Normal import functionality", "Standard file formats supported",
    "Adequate mobile compatibility", "Typical responsive design", "Standard browser support",
    "Regular API documentation", "Normal integration methods", "Standard webhook support",
    "Adequate search functionality", "Typical filtering options", "Standard sorting capabilities",
    "Regular notification system", "Normal alert mechanisms", "Standard reminder features",
    "Adequate collaboration tools", "Typical sharing options", "Standard permission settings",
    "Regular version control", "Normal change tracking", "Standard audit trail",
    "Adequate dashboard layout", "Typical widget options", "Standard chart types",
    "Regular data visualization", "Normal graph capabilities", "Standard table formatting",
    "Adequate calendar integration", "Typical scheduling features", "Standard meeting tools",
    "Regular task management", "Normal project tracking", "Standard milestone features",
    "Adequate resource planning", "Typical capacity management", "Standard workload distribution",
    "Regular performance tracking", "Normal productivity metrics", "Standard efficiency measures",
    "Adequate time tracking", "Typical timesheet functionality", "Standard billing integration",
    "Regular expense tracking", "Normal budget management", "Standard financial reporting",
    "Adequate ROI calculations", "Typical cost analysis", "Standard profit tracking",
    "Regular market analysis", "Normal competitive research", "Standard benchmarking tools",
    "Adequate customer management", "Typical CRM functionality", "Standard contact organization",
    "Regular sales tracking", "Normal pipeline management", "Standard deal tracking",
    "Adequate lead generation", "Typical conversion tracking", "Standard funnel analysis",
    "Regular email marketing", "Normal campaign management", "Standard automation features",
    "Adequate social media tools", "Typical posting capabilities", "Standard analytics integration",
    "Regular content management", "Normal publishing workflow", "Standard editorial calendar",
    "Adequate SEO features", "Typical optimization tools", "Standard keyword tracking",
    "Regular website analytics", "Normal traffic reporting", "Standard conversion tracking",
    "Adequate e-commerce features", "Typical shopping cart", "Standard payment processing",
    "Regular inventory management", "Normal stock tracking", "Standard order processing",
    "Adequate shipping integration", "Typical carrier support", "Standard tracking capabilities",
    "Regular customer service tools", "Normal ticket management", "Standard help desk features",
    "Adequate knowledge base", "Typical FAQ system", "Standard self-service options",
    "Regular training modules", "Normal certification paths", "Standard skill assessments",
    "Adequate HR functionality", "Typical employee management", "Standard payroll integration",
    "Regular recruitment tools", "Normal applicant tracking", "Standard interview scheduling",
    "Adequate performance reviews", "Typical evaluation forms", "Standard feedback collection",
    "Regular compliance tracking", "Normal policy management", "Standard regulatory reporting",
    "Adequate risk assessment", "Typical threat monitoring", "Standard vulnerability scanning",
    "Regular security updates", "Normal patch management", "Standard incident response",
    "Adequate backup systems", "Typical recovery options", "Standard disaster planning",
    "Regular system monitoring", "Normal uptime tracking", "Standard performance alerts",
    "Adequate load balancing", "Typical failover systems", "Standard redundancy planning",
    "Regular capacity planning", "Normal resource allocation", "Standard usage monitoring",
    "Adequate cost optimization", "Typical budget controls", "Standard expense management",
    "Regular vendor management", "Normal supplier tracking", "Standard contract management",
    "Adequate procurement tools", "Typical purchasing workflow", "Standard approval processes",
    "Regular asset management", "Normal inventory tracking", "Standard depreciation calculations",
    "Adequate facility management", "Typical space planning", "Standard maintenance scheduling",
    "Regular environmental monitoring", "Normal energy tracking", "Standard sustainability reporting",
    "Adequate quality management", "Typical process controls", "Standard improvement tracking",
    "Regular audit preparation", "Normal compliance checking", "Standard documentation management",
    "Adequate change management", "Typical workflow approval", "Standard version tracking",
    "Regular communication tools", "Normal messaging features", "Standard notification systems",
    "Adequate file sharing", "Typical cloud storage", "Standard synchronization features",
    "Regular collaboration spaces", "Normal team workspaces", "Standard project areas",
    "Adequate video conferencing", "Typical meeting features", "Standard screen sharing",
    "Regular webinar capabilities", "Normal presentation tools", "Standard recording options",
    "Adequate survey tools", "Typical form builders", "Standard response collection",
    "Regular feedback systems", "Normal rating mechanisms", "Standard review processes",
    "Adequate analytics platform", "Typical data processing", "Standard visualization tools",
    "Regular reporting engine", "Normal dashboard creation", "Standard metric tracking",
    "Adequate business intelligence", "Typical data mining", "Standard trend analysis",
    "Regular forecasting tools", "Normal predictive models", "Standard scenario planning",
    "Adequate workflow automation", "Typical process optimization", "Standard efficiency tools",
    "Regular integration platform", "Normal API management", "Standard data synchronization",
    "Adequate development tools", "Typical coding environment", "Standard debugging features",
    "Regular testing framework", "Normal quality assurance", "Standard deployment tools",
    "Adequate version control", "Typical repository management", "Standard branch handling",
    "Regular continuous integration", "Normal build automation", "Standard release management",
    "Adequate monitoring solutions", "Typical log management", "Standard error tracking",
    "Regular performance optimization", "Normal resource tuning", "Standard efficiency improvements",
    "Adequate scalability planning", "Typical growth management", "Standard expansion support",
    "Regular maintenance windows", "Normal update procedures", "Standard downtime scheduling",
    "Adequate user training", "Typical skill development", "Standard competency building",
    "Regular certification programs", "Normal assessment tools", "Standard validation processes",
    "Adequate support documentation", "Typical help resources", "Standard troubleshooting guides",
    "Regular community forums", "Normal user groups", "Standard knowledge sharing",
    "Adequate feedback channels", "Typical suggestion systems", "Standard improvement requests",
    "Regular product updates", "Normal feature releases", "Standard enhancement delivery",
    "Adequate roadmap planning", "Typical development cycles", "Standard release schedules",
    "Regular market research", "Normal competitive analysis", "Standard industry benchmarking",
    "Adequate customer surveys", "Typical satisfaction tracking", "Standard loyalty measurement",
    "Regular usage analytics", "Normal behavior tracking", "Standard engagement metrics",
    "Adequate retention analysis", "Typical churn tracking", "Standard lifetime calculations",
    "Regular revenue reporting", "Normal profit analysis", "Standard financial metrics",
    "Adequate growth tracking", "Typical expansion metrics", "Standard market penetration",
    "Regular brand monitoring", "Normal reputation tracking", "Standard sentiment analysis",
    "Adequate social listening", "Typical mention tracking", "Standard influence measurement",
    "Regular content performance", "Normal engagement tracking", "Standard reach analysis",
    "Adequate campaign results", "Typical conversion metrics", "Standard attribution modeling",
    "Regular A/B testing", "Normal experiment design", "Standard statistical analysis",
    "Adequate personalization", "Typical recommendation systems", "Standard targeting capabilities",
    "Regular segmentation tools", "Normal audience analysis", "Standard demographic tracking",
    "Adequate journey mapping", "Typical touchpoint analysis", "Standard experience tracking",
    "Regular optimization tools", "Normal improvement processes", "Standard enhancement workflows"
]

# Create 1000 unique entries
data = []
all_comments = positive_comments + negative_comments + neutral_comments

# Ensure we have enough unique comments
if len(all_comments) < 1000:
    # If we don't have enough, we'll cycle through but ensure uniqueness within each sentiment
    pos_count = 334
    neg_count = 333
    neu_count = 333
    
    # Add positive comments
    for i in range(pos_count):
        data.append([positive_comments[i % len(positive_comments)], 'Positive'])
    
    # Add negative comments
    for i in range(neg_count):
        data.append([negative_comments[i % len(negative_comments)], 'Negative'])
    
    # Add neutral comments
    for i in range(neu_count):
        data.append([neutral_comments[i % len(neutral_comments)], 'Neutral'])
else:
    # We have enough unique comments
    selected_pos = random.sample(positive_comments, 334)
    selected_neg = random.sample(negative_comments, 333)
    selected_neu = random.sample(neutral_comments, 333)
    
    for comment in selected_pos:
        data.append([comment, 'Positive'])
    for comment in selected_neg:
        data.append([comment, 'Negative'])
    for comment in selected_neu:
        data.append([comment, 'Neutral'])

# Shuffle the data
random.shuffle(data)

# Write CSV
with open('testdata.csv', 'w') as f:
    f.write('A,B\n')
    for row in data:
        f.write(f'"{row[0]}",{row[1]}\n')

print('CSV with 1000 unique rows created successfully')